# Generated by Django 6.1.1 on 2026-09-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fir_artifacts", "0008_alter_artifact_incidents_alter_file_incident"),
        ("incidents", "0018_comments_comments_in_opened_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="incidentartifact",
            index=models.Index(
                fields=["artifact", "incident"], name="ia_artifact_inc_idx"
            ),
        ),
    ]
