# Generated by Django 6.1.1 on 2026-09-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fir_todos", "0006_auto_20210209_0717"),
        ("incidents", "0018_comments_comments_in_opened_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="todoitem",
            index=models.Index(fields=["done", "incident"], name="todo_done_inc_idx"),
        ),
    ]
