# Generated by Django 6.1.1 on 2026-09-13 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0017_move_file_artifact_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comments',
            index=models.Index(fields=['incident', 'opened_by'], name='comments_in_opened_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['-date'], name='incident_date_idx'),
        ),
    ]
